// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `init_logger`, `take_camera_hub_thread`

Future<String> getAndroidCameraSpecsJson({
  required int displayWidth,
  required int displayHeight,
}) => RustLib.instance.api.crateApiGetAndroidCameraSpecsJson(
  displayWidth: displayWidth,
  displayHeight: displayHeight,
);

Future<void> setAndroidCameraSettings({
  required int facing,
  required int width,
  required int height,
  required int frameRateMin,
  required int frameRateMax,
}) => RustLib.instance.api.crateApiSetAndroidCameraSettings(
  facing: facing,
  width: width,
  height: height,
  frameRateMin: frameRateMin,
  frameRateMax: frameRateMax,
);

Future<void> startAndroidCameraHub({
  required String workDir,
  required String serverUsername,
  required String serverPassword,
  required String serverAddr,
}) => RustLib.instance.api.crateApiStartAndroidCameraHub(
  workDir: workDir,
  serverUsername: serverUsername,
  serverPassword: serverPassword,
  serverAddr: serverAddr,
);

Future<void> resetAndroidCameraHub({
  required String workDir,
  required String serverUsername,
  required String serverPassword,
  required String serverAddr,
}) => RustLib.instance.api.crateApiResetAndroidCameraHub(
  workDir: workDir,
  serverUsername: serverUsername,
  serverPassword: serverPassword,
  serverAddr: serverAddr,
);

Future<void> stopAndroidCameraHub() =>
    RustLib.instance.api.crateApiStopAndroidCameraHub();
