// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `init_logger`, `take_camera_hub_thread`

Future<void> startAndroidCameraHub({
  required String workDir,
  required String serverUsername,
  required String serverPassword,
  required String serverAddr,
}) => RustLib.instance.api.crateApiStartAndroidCameraHub(
  workDir: workDir,
  serverUsername: serverUsername,
  serverPassword: serverPassword,
  serverAddr: serverAddr,
);

Future<void> resetAndroidCameraHub({
  required String workDir,
  required String serverUsername,
  required String serverPassword,
  required String serverAddr,
}) => RustLib.instance.api.crateApiResetAndroidCameraHub(
  workDir: workDir,
  serverUsername: serverUsername,
  serverPassword: serverPassword,
  serverAddr: serverAddr,
);

Future<void> stopAndroidCameraHub() =>
    RustLib.instance.api.crateApiStopAndroidCameraHub();
